apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .Values.namespace }}-og
  namespace: {{ .Values.namespace }}
spec:
  targetNamespaces:
  - {{ .Values.namespace }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: argocd-operator
  namespace: {{ .Values.namespace }}
spec:
  channel: {{ .Values.channel | quote }}
  installPlanApproval: Automatic
  name: argocd-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: {{ .Values.startingCSV }}